### ISSUE TITLE
error: discord 4014

### ISSUE THREAD

**Issue by DBraspberrypi** [abobija/esp-discord#6]
tried to run the example code echo but resulting in a 4014 error from discord due to "disallowed intents" even though the bot has been given admin rights

W (239053) TRANSPORT_WS: esp_transport_ws_poll_connection_closed: unexpected data readable on socket=54
W (239053) WEBSOCKET_CLIENT: Connection terminated while waiting for clean TCP close
E (239713) DISCORD: dc_task: Connection closed (code=4014, desc=Disallowed intent(s).)
I (239713) DISCORD: dc_task: Restarting discord in 10 sec...

**Comment by mstcgalis** [comment]
hi,
i just got the exact same error, did you manage to figure it out?

**Comment by mstcgalis** [comment]
read the [Discord Gateway docs](https://discord.com/developers/docs/topics/gateway#privileged-intents) and it turns out toggling these options on will make privileged intents work :)

![Screenshot 2023-05-23 at 19 10 33](https://github.com/abobija/esp-discord/assets/77400726/1eee7eb8-6e35-4d07-b3ce-2717bce04e7b)

i think this issue can be closed.

**Comment by abobija** [comment]
@mstcgalis thanks for the investigation and posting the fix here
